### ISSUE TITLE
batched_gather  error

### ISSUE THREAD

**Issue by lfs119** [bjing2016/mdgen#2]
![image](https://github.com/user-attachments/assets/8606b5fd-bd4c-403d-a48f-ff424747d683)

Hi,  when i run tps_inference.py.  I got a error : (IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (1,4) (4,37)) in def batched_gather()

**Comment by Exchen0** [comment]
Hi, I encountered the same issue when running tps_inference.py. I was wondering if you managed to solve this problem? If so, could you share how you fixed it? Thank you!

**Comment by ayankashyap** [comment]
I would like to know this was fixed as well. Having the same error while running forward simulation on atlas

**Comment by lfs119** [comment]
@ayankashyap @Exchen0     def get_sample

![image](https://github.com/user-attachments/assets/222d6f7c-f2f2-4bea-b07e-26658611bb80)
